version: '3'

services:

  php:
    build: .
    image: yuttasakcom/dm-php:1.0.0
    container_name: php
    networks:
      - web
      - db
    volumes:
      - ~/workspace/www:/var/www/html
    deploy:
      placement:
        constraints:
          - node.labels.tag == node1
      replicas: 2
    restart: always

networks:
  web:
    external: true
  db:
    external: true
