version: '3'

services:

  php:
    build: .
    image: yuttasakcom/dm-php:1.0.0
    container_name: php
    networks:
      - web
    volumes:
      - ~/workspace/www:/var/www/html
    restart: always

networks:
  web:
    external: true
