version: '3'

services:

  proxy:
    build: .
    image: yuttasakcom/proxy:1.0
    container_name: proxy
    networks:
      - proxy
    ports:
      - "80:80"
    restart: always

networks:
  proxy:
    external: true