version: '3'

services:

  mariadb:
    image: mariadb:10.2.10
    container_name: db
    volumes:
      - /data/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    networks:
      - mariadb
    restart: always

networks:
  mariadb:
    driver: bridge