version: '3'

services:

  mariadb:
    image: mariadb:10.2.12
    container_name: mariadb
    volumes:
      # - /data/mariadb:/var/lib/mysql
      - db-data:/var/lib/mysql/data
    env_file:
      - ./.env
    networks:
      - db
    deploy:
      placement:
        constraints:
          - node.labels.tag == db
    restart: always

volumes:
  db-data:

networks:
  db:
    external: true