version: '3'

services:

  mariadb:
    image: mariadb:10.2.12
    container_name: mariadb
    volumes:
      - /data/mariadb:/var/lib/mysql
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    networks:
      - db
    deploy:
      placement:
        constraints:
          - node.labels.tag == db
    restart: always

networks:
  db:
    external: true