version: '3.5'

services:

  mariadb:
    image: mariadb:10.3.7
    container_name: mariadb
    volumes:
      - /data/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=project_c
    ports:
      - "3306:3306"
    restart: always