version: '3.5'

services:

  mongodb:
    image: mongo:3.6.5
    container_name: mongodb
    env_file:
      - ./.env
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/data/db
    restart: always