version: '3'

services:

  mongodb:
    image: mongo:3.6.3
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - /data/mongodb:/data/db
    networks:
      - db
    restart: always
  
networks:
  db:
    external: true