version: '3.5'

services:

  mongodb:
    image: mongo:3.6.3
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data_mongo:/data/db
    networks:
      - db
    restart: always

volumes:
  data_mongo:
  
networks:
  db:
    external: true