version: '3'

services:

  redis:
    image: redis:4.0.8
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - /data/redis:/data
    networks:
      - db
    restart: always

networks:
  db:
    external: true