version: '3'

services:

  redis:
    image: redis:4.0.2
    ports:
      - "6379:6379"
    volumes:
      - /data/redis:/data
      # - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis
    restart: always

networks:
  redis:
    driver: bridge