version: '3.1'

services:

  proxy:
    build: .
    image: yuttasakcom/dm-proxy:1.0.0
    container_name: proxy
    networks:
      - proxy
    ports:
      - "80:80"
    restart: always

networks:
  proxy:
    external: true