version: '3'

services:

  web:
    build: .
    image: yuttasakcom/dm-nginx:1.0.3
    container_name: web
    networks:
      - proxy
      - web
      - db
    volumes:
      - ~/workspace/www:/var/www/html
    restart: always

networks:
  proxy:
    external: true
  web:
    external: true
  db:
    external: true