version: '3'

services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7.4-1
    depends_on:
      - mariadb:db
    ports:
      - "8088:80"
    networks:
      - db
    restart: always

networks:
  db:
    external: true