version: '3'

services:

  mongo:
    image: mongo:3.4.9
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/mongo:/data/db
    networks:
      - mongo
    restart: always

networks:
  mongo:
    driver: bridge